# Generated by Django 3.1.5 on 2021-01-12 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0003_auto_20210111_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=164)),
                ('logo', models.ImageField(blank=True, upload_to='media/teams')),
                ('description', models.TextField(blank=True)),
                ('password', models.CharField(max_length=50)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_manager', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='team_member', to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.sport')),
            ],
        ),
    ]
