# Generated by Django 3.1.5 on 2021-01-16 07:49

from django.db import migrations, models
import teams.models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, upload_to=teams.models.team_upload_to),
        ),
    ]
