# Generated by Django 3.1.5 on 2021-09-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210111_1636'),
        ('teams', '0002_auto_20210116_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='team_member', to='profiles.Profile'),
        ),
    ]
