# Generated by Django 3.1.5 on 2021-09-05 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0005_auto_20210905_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='team_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
