# Generated by Django 3.1.5 on 2021-01-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210110_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ('area',)},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'ordering': ('sport',)},
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
