# Generated by Django 3.1.5 on 2021-01-16 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import eventmanage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_auto_20210111_1636'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0002_auto_20210116_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=164, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=164)),
                ('logo', models.ImageField(blank=True, upload_to=eventmanage.models.manager_upload_to)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_event', models.BooleanField(default=False)),
                ('min_team', models.IntegerField(blank=True, null=True)),
                ('max_team', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(blank=True)),
                ('time', models.TimeField(blank=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=256)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('banner', models.ImageField(blank=True, upload_to=eventmanage.models.event_upload_to)),
                ('poster', models.ImageField(blank=True, upload_to=eventmanage.models.event_upload_to)),
                ('payment_required', models.BooleanField(default=False)),
                ('payment_gateway', models.URLField(blank=True, null=True)),
                ('payment_number', models.CharField(blank=True, max_length=16, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('event_created', models.DateTimeField(auto_now=True)),
                ('registration_open', models.BooleanField(default=True)),
                ('instruction', models.TextField(blank=True)),
                ('register_localy', models.BooleanField(default=True)),
                ('external_link', models.URLField(blank=True)),
                ('State', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='profiles.area')),
                ('event_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='eventmanage.eventtype')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='eventmanage.manager')),
                ('payment_methods', models.ManyToManyField(blank=True, to='eventmanage.PaymentMethod')),
                ('registrants', models.ManyToManyField(blank=True, related_name='registrants', to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event', to='profiles.sport')),
                ('teams', models.ManyToManyField(blank=True, related_name='registered_teams', to='teams.Team')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=168)),
                ('short_description', models.TextField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=256)),
                ('phone', models.TextField(blank=True, max_length=16)),
                ('community_logo', models.ImageField(blank=True, upload_to=eventmanage.models.community_upload_to)),
                ('community_banner', models.ImageField(blank=True, upload_to=eventmanage.models.community_upload_to)),
                ('community_poster', models.ImageField(blank=True, upload_to=eventmanage.models.community_upload_to)),
                ('area', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.area')),
                ('manager', models.ManyToManyField(related_name='secondary_manager', to='eventmanage.Manager')),
                ('members', models.ManyToManyField(blank=True, related_name='community', to=settings.AUTH_USER_MODEL)),
                ('primary_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_manager', to='eventmanage.manager')),
                ('sport', models.ManyToManyField(to='profiles.Sport')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=64)),
                ('transaction_time', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_event', to='eventmanage.event')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trasaction_method', to='eventmanage.paymentmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'order_with_respect_to': 'event',
            },
        ),
    ]
