# Generated by Django 3.1.5 on 2021-01-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanage', '0002_event_payment_instruction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='State',
            new_name='state',
        ),
        migrations.AddField(
            model_name='event',
            name='facebook',
            field=models.URLField(blank=True),
        ),
    ]
